[toolchain]
channel = "nightly-2026-02-08"
targets = ["x86_64-unknown-none", "x86_64-unknown-linux-musl", "i686-unknown-linux-musl", "x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]
components = ["clippy", "rust-src", "rustfmt"]
