[package]
name = "external-tests-wrapper"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.81"
nix = { version = "0.31.1", default-features = false, features = ["mount", "process", "time"] }
tar = "0.4.40"
